### ISSUE TITLE
有个问题实在需要问下大兄弟？

### ISSUE THREAD

**Issue by huyansheng3** [bubkoo/bubkoo.github.com#2]
http://bubkoo.com/2016/03/26/delivering-octicons-with-svg/

这里提到了将 iconfont 替换成了 svg，有一个问题，如何方便的控制 svg 大小。

原来的 iconfont的话只需要修改 font-size 就可以方便的控制图标大小了，

svg 的话，不能直接修改 width 和 height，用 transform scale 可以改大小，但是占位空间还在，怎么弄比较好呢？

**Comment by bubkoo** [comment]
@huyansheng3 为什么不能直接修改 width 和 height 呢？场景是怎么样的

**Comment by huyansheng3** [comment]
知道问题了，改 viewport 会有问题，改 width 和 height 不会有问题。
原本以为元素会被切割，实际看到会等比例缩放。
